title: Crucible - FIX Exchange System
description: Real-time FIX Protocol Exchange with WebSocket Dashboard
theme: jekyll-theme-cayman
show_downloads: true
github:
  repository_url: https://github.com/sc895/Crucible

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true
